SELECT 
    CUSTOMER_ID,
    MAX(PURCHASE_AMOUNT) AS "Highest Purchase Amount"
FROM ORDERS_ACTIVITY6
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID;

SELECT 
    SALESMAN_ID,
    MAX(PURCHASE_AMOUNT) AS "Highest Purchase (2012-08-17)"
FROM ORDERS_ACTIVITY6
WHERE ORDER_DATE = TO_DATE('2012-08-17', 'YYYY-MM-DD')
GROUP BY SALESMAN_ID
ORDER BY SALESMAN_ID;

SELECT 
    CUSTOMER_ID,
    MAX(PURCHASE_AMOUNT) AS "Highest Purchase Amount",
    MAX(ORDER_DATE) KEEP (DENSE_RANK FIRST ORDER BY PURCHASE_AMOUNT DESC) AS "Order Date"
FROM ORDERS_ACTIVITY6
GROUP BY CUSTOMER_ID
HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000)
ORDER BY CUSTOMER_ID;
